Add action for releasing swift-syntax

diff --git a/.github/workflows/build-publish.yml b/.github/workflows/build-publish.yml
--- a/.github/workflows/build-publish.yml
+++ b/.github/workflows/build-publish.yml
@@ -13,10 +13,18 @@ jobs:
     runs-on: macos-13
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      BUILD_TARGET: //:SwiftSyntax_opt
       ARCHIVE_NAME: swift-syntax-${{ github.event.inputs.tag }}
-      RULES_SWIFT_VERSION: 1.15.1
+      XCODE_VERSION: 15.1
+      SUPPORTED_ARCHS: ("x86_64" "arm64")
+      RULES_SWIFT_VERSION: 1.5.1
+      RULES_APPLE_VERSION: 2.0.0
+      MACOS_VERSION: 13.0
     steps:
+      - name: Install brew dependencies
+        run: |
+          brew install buildozer
+      - name: Select Xcode ${{ env.XCODE_VERSION }}
+        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
       - name: Clone repo
         uses: actions/checkout@v4
       - name: Clone SwiftSyntax
@@ -27,33 +35,11 @@ jobs:
             --single-branch
       - name: Build & Publish SwiftSyntax prebuilt binary
         run: |
-          cd swift-syntax
+          set -euo pipefail
 
-          # Collect the list of files that are used to build SwiftSyntax.
-          outputs=$(bazel cquery ${{ env.BUILD_TARGET }} --output=files)
+          archs=${{ env.SUPPORTED_ARCHS }}
 
-          # Build SwiftSyntax.
-          bazel build ${{ env.BUILD_TARGET }}
-
-          # Copy the outputs to the archive directory.
           mkdir -p ${{ env.ARCHIVE_NAME }}
-          for output in $outputs; do
-            cp -R $output ${{ env.ARCHIVE_NAME }}
-          done
-
-          # Create the BUILD file which will be used to include SwiftSyntax as a dependency.
-          cat > ${{ env.ARCHIVE_NAME }}/BUILD.bazel <<EOF
-          load("@build_bazel_rules_swift//swift:swift.bzl", "swift_import")
-
-          swift_import(
-              name = "SwiftSyntax_opt",
-              archives = ["libSwiftSyntax.a"],
-              module_name = "SwiftSyntax",
-              swiftdoc = "SwiftSyntax.swiftdoc",
-              swiftmodule = "SwiftSyntax.swiftmodule",
-              visibility = ["//visibility:public"],
-          )
-          EOF
 
           # Create the MODULE.bazel file which will be used to include SwiftSyntax as a bazel_dep via archive_override.
           cat > ${{ env.ARCHIVE_NAME }}/MODULE.bazel <<EOF
@@ -64,22 +50,134 @@ jobs:
           )
 
           bazel_dep(
-              name = "rules_swift",
-              version = "${{ env.RULES_SWIFT_VERSION }}",
-              repo_name = "build_bazel_rules_swift",
+            name = "platforms",
+            version = "0.0.8",
+          )
+
+          bazel_dep(
+            name = "rules_swift",
+            version = "${{ env.RULES_SWIFT_VERSION }}",
+            repo_name = "build_bazel_rules_swift",
           )
           EOF
+
+          # Create the BUILD file which will be used to include the exposed targets.
+          cat > ${{ env.ARCHIVE_NAME }}/BUILD.bazel <<EOF
+          load("@build_bazel_rules_swift//swift:swift.bzl", "swift_import")
+
+          config_setting(
+              name = "darwin_x86_64",
+              constraint_values = [
+                  "@platforms//os:macos",
+                  "@platforms//cpu:x86_64",
+              ],
+          )
+
+          config_setting(
+              name = "darwin_arm64",
+              constraint_values = [
+                  "@platforms//os:macos",
+                  "@platforms//cpu:aarch64",
+              ],
+          )
+
+          EOF
+
+          # -- start swift-syntax build --
+          pushd swift-syntax
+
+          # TODO: for swift-syntax 508-509 there is a missing dep on `SwiftOperators` which causes build to fail.
+          # Use buildozer to add the missing dep.
+          buildozer "add deps :SwiftOperators" //:SwiftSyntaxMacros
+
+          # Shared build flags:
+          #  - set the minimum macOS version to the version specified in the workflow input
+          #  - set the host macOS version to the version specified in the workflow input
+          #  - enable library evolution
+          build_flags=(
+            --macos_minimum_os="${{ env.MACOS_VERSION }}"
+            --host_macos_minimum_os="${{ env.MACOS_VERSION }}"
+            --features="swift.enable_library_evolution"
+          )
+
+          # Collect the labels for the targets that will be exported.
+          # Targets exported are those suffixed with `_opt`.
+          # The cquery output looks like: `//:SwiftBasicFormat_opt (5d78ae7)` and we take just the label.
+          labels=($(bazel cquery "filter(_opt, //...)" "${build_flags[@]}" | sed 's/ (.*//'))
+
+          # Create the BUILD file for each of the swift-syntax targets.
+          for label in ${labels[@]}; do
+            # Collect information about the target, we need deps to be propagated to downstream targets.
+            non_opt_label=$(echo $label | sed 's/_opt$//')
+            module_name=$(buildozer "print name" $non_opt_label)
+            dependencies=$(buildozer "print deps" $non_opt_label | sed 's/^\[//' | sed 's/\]$//')
+
+            # Create the `swift_import` target for this module.
+            # Do this in the directory to make it easier to use buildozer with labels.
+            pushd ../${{ env.ARCHIVE_NAME }}
+            buildozer "new swift_import ${module_name}_opt" //:__pkg__
+            buildozer "set module_name \"${module_name}\"" //:${module_name}_opt
+            buildozer "set visibility \"//visibility:public\"" //:${module_name}_opt
+            buildozer "set_select archives :darwin_x86_64 \"x86_64/lib${module_name}.a\" :darwin_arm64 \"arm64/lib${module_name}.a\"" //:${module_name}_opt
+            buildozer "set_select swiftmodule :darwin_x86_64 \"x86_64/${module_name}.swiftmodule\" :darwin_arm64 \"arm64/${module_name}.swiftmodule\"" //:${module_name}_opt
+            buildozer "set_select swiftdoc :darwin_x86_64 \"x86_64/${module_name}.swiftdoc\" :darwin_arm64 \"arm64/${module_name}.swiftdoc\"" //:${module_name}_opt
+            if [ -n "$dependencies" ]; then
+              # Add '_opt' to each word in the dependencies list and set the deps.
+              dependencies=($(echo $dependencies | sed 's/ /_opt /g')_opt)
+              buildozer "set deps ${dependencies[*]}" //:${module_name}_opt
+            fi
+            popd
+          done
+
+          # Build the module for each architecture we suppport.
+          for arch in ${archs[@]}; do
+            echo "Building ${labels[@]} for: $arch"
+            arch_flags=("--cpu=darwin_${arch}")
+            outputs=$(bazel cquery "set(${labels[@]})" --output=files "${build_flags[@]}" "${arch_flags[@]}")
+            bazel build "${labels[@]}" "${build_flags[@]}" "${arch_flags[@]}"
+
+            # Copy the .swiftmodule, .a, .swiftdoc file to the archive directory within a subdirectory for the architecture.
+            for output in $outputs; do
+              if [[ $output == *.swiftmodule || $output == *.a || $output == *.swiftdoc ]]; then
+                output_name=$(basename "$output")
+                archive_dir_path="../${{ env.ARCHIVE_NAME }}/${arch}"
+                mkdir -p "$archive_dir_path"
+                archive_path="$archive_dir_path/${output_name}"
+                echo "Copying $output to $archive_path"
+                cp -R "$output" "$archive_path"
+              fi
+            done
+          done
+
+          popd
+          # -- end swift-syntax build --
 
           # Package the outputs into a tarball.
           tar -czf ${{ env.ARCHIVE_NAME }}.tar.gz ${{ env.ARCHIVE_NAME }}
 
-          # Move the tarball to the repo.
-          # NOTE: this is required so gh can release based on this repository and not the swift-syntax repository.
-          mv ${{ env.ARCHIVE_NAME }}.tar.gz ../
-          cd ../
+          # Generate the expected sha256 checksum for the tarball.
+          bzlmod_sha256=$(openssl dgst -sha256 -binary ${{ env.ARCHIVE_NAME }}.tar.gz | openssl base64 -A | sed 's/^/sha256-/')
+
+          # Make the release notes
+          cat > release-notes.md <<EOF
+          # SwiftSyntax ${{ github.event.inputs.tag }}
+
+          This release contains the pre-built binaries for SwiftSyntax ${{ github.event.inputs.tag }}.
+
+          Use in your \`MODULE.bazel\` file with \`archive_override\`:
+
+            \`\`\`starlark
+            archive_override(
+                module_name = "swift-syntax",
+                integrity = "$bzlmod_sha256",
+                strip_prefix = "swift-syntax-${{ github.event.inputs.tag }}",
+                urls = ["https://github.com/square/swift-syntax-prebuilt/releases/download/${{ github.event.inputs.tag }}/swift-syntax-${{ github.event.inputs.tag }}.tar.gz"],
+            )
+            \`\`\`
+          EOF
 
           # Publish the tarball to GitHub Releases.
           gh release create ${{ github.event.inputs.tag }} \
             --title ${{ github.event.inputs.tag }} \
-            --notes "SwiftSyntax ${{ github.event.inputs.tag }} as a prebuilt binary" \
+            --notes-file release-notes.md \
             ${{ env.ARCHIVE_NAME }}.tar.gz
